- README.md
- lerna.json
- package.json
- packages/components/button-group/package.json
- packages/components/button/package.json
- packages/components/root/package.json
- packages/core/package.json
In order to show more info to npm and add publish command
@sampi
> Add more information to package.json

- README.md
- lerna.json
- package-lock.json
- package.json
- packages/components/button-group/package.json
- packages/components/button/package.json
- packages/components/root/package.json
- packages/components/tooltip/package.json
- packages/components/typography/package.json
- packages/components/typography/src/typography.css
- packages/components/typography/src/typography.js
- packages/components/typography/stories/typography.stories.js
- packages/core/package.json
- rollup.globals.json
A text component to make texts look consistent over the whole application.
- _**text**_
- **_color_**: default, error, danger, warning, action, primary
- **_variant_**: default, title, subtitle
- _**no-wrap**_
> Add typography component

- package-lock.json
- package.json
- packages/components/progress-bar/package.json
- packages/components/progress-bar/src/progress-bar.css
- packages/components/progress-bar/src/progress-bar.js
- packages/components/progress-bar/stories/progress-bar.stories.js
- packages/core/src/vars.css
- rollup.globals.json
Progress bar component with two different mode, determinate and indeterminate.
- _**indeterminate**_
- _**total**_
- _**done**_
> Add progress bar component

- index.html
- package-lock.json
- package.json
- packages/components/card/package.json
- packages/components/card/src/card.css
- packages/components/card/src/card.js
- packages/components/card/stories/card.stories.js
- packages/core/src/vars.css
- rollup.globals.json
Card component
- _**type**_ : default, (error, failed, danger), success, (active, focus, primary) 
- _**size**_: full, medium, small
- _**orientation**_: (vertical,v), (horizontal,h)
- _**rtl**_
- _**no-padding**_
- _**no-horizontal-padding**_
- _**no-vertical-padding**_
> Add card component

- package.json
- packages/components/file-uploader-input/package.json
- packages/components/file-uploader-input/src/file-uploader-input.css
- packages/components/file-uploader-input/src/file-uploader-input.js
- packages/components/file-uploader-input/stories/file-uploader-input.stories.js
- rollup.globals.json
Add file uploader input component
- _**disabled**_
- _**rtl**_
- _**multiple**_
- _**size**_ : full, samll, medium
- _**accepted-file-extensions**_
- _**disable-drag-and-drop**_
> Add file uploader input component

- index.html
- packages/components/file-card/src/file-card.css
- packages/components/file-card/src/file-card.js
Fix size and hover state of file card
> Fix file card

- packages/core/package.json
> Include src in the core package

- .travis.yml
> Disable happo right now. Because we took too many screenshots

- packages/components/file-card/src/file-card.css
- packages/components/typography/src/typography.css
Fix file card text jumping issue when action messages are shown!
> Fix file card text jumping

- index.html
- packages/components/file-uploader-input/src/file-uploader-input.css
- packages/components/file-uploader-input/src/file-uploader-input.js
- packages/components/help-text/src/help-text.css
- packages/core/src/vars.css
> File uploader input UI fixes

- package-lock.json
- package.json
- rollup.config.js
Now the browser reload the page after each file change
It's not perfect yet and need some modification in future but for sure better than nothing!
> Change development server

- lerna.json
- package-lock.json
- package.json
- packages/components/button-group/package.json
- packages/components/button/package.json
- packages/components/card/package.json
- packages/components/file-card/package.json
- packages/components/file-size/package.json
- packages/components/file-uploader-input/package.json
- packages/components/help-text/package.json
- packages/components/progress-bar/package.json
- packages/components/root/package.json
- packages/components/tooltip/package.json
- packages/components/typography/package.json
- packages/core/package.json
- rollup.config.js
V4 will find mjs if we include it. But it has some conflicts with V4 webpack. 
I have to change it to umd
@esmailpour-hosein
> Change the package  json to remove the mjs

- .prettierrc
- packages/components/card/src/card.css
- packages/components/file-card/src/file-card.css
- packages/components/file-uploader-input/src/file-uploader-input.css
- packages/components/file-uploader-input/stories/file-uploader-input.stories.js
- packages/components/root/src/root.css
- packages/components/typography/src/typography.css
- packages/core/src/fonts.css
- packages/core/src/vars.css
Fix the problem with the height of file card and drop state height to don't cause a twitch
> Fix file uploader height

- packages/components/file-uploader-input/src/file-uploader-input.css
- Fixes issue [#76](https://github.com/Tradeshift/elements/issues/76)
> Fix file uploader IE flex bug

- README.md
- package.json
- packages/components/button-group/README.md
- packages/components/button/README.md
- packages/components/card/README.md
- packages/components/file-card/README.md
- packages/components/file-size/README.md
- packages/components/file-uploader-input/README.md
- packages/components/help-text/README.md
- packages/components/icon/README.md
- packages/components/progress-bar/README.md
- packages/components/root/README.md
- packages/components/tooltip/README.md
- packages/components/typography/README.md
Add more information about how to use it and how to contribute
Add badges
Move polyfills limitation to wiki page
issue #70
> Update readme file

- packages/components/file-uploader-input/src/file-uploader-input.js
- packages/components/help-text/src/help-text.css
- packages/components/icon/src/icon.css
Fix long help text issue in ie11
fix icon hover color
> Fix long help text issue in ie11

- index.css
- index.html
- packages/components/button/src/button.css
- packages/components/button/src/button.js
- packages/components/button/stories/button.happo.js
- packages/components/button/stories/button.stories.js
- packages/core/src/vars.css
Fix border in disabled mode
Fix issue #102
> Add new stories to button

- packages/components/button/src/button.css
- packages/components/card/stories/card.happo.js
- packages/components/cover/src/cover.css
- packages/components/cover/src/cover.js
- packages/components/file-card/stories/file-card.happo.js
- packages/components/file-uploader-input/src/file-uploader-input.css
- packages/components/file-uploader-input/src/file-uploader-input.js
- packages/components/file-uploader-input/stories/file-uploader-input.happo.js
- packages/components/help-text/src/help-text.css
- packages/components/help-text/stories/help-text.happo.js
- packages/core/src/common.css
Fix file uploader input hover border
Fix icon and alignment issues on IOS
> Fix file uploader issues

- index.html
- package.json
- packages/components/file-uploader-input/src/file-uploader-input.css
- packages/components/file-uploader-input/src/file-uploader-input.js
accepted file type was unnecessarily required and fixed that! Also for the accepted file types there was an issue with the conditional attribute which is fixed now!
Fixes issue #122
@zdlm
> Fix file uploader input accepted file types

- index.css
- index.html
- package-lock.json
- package.json
- packages/components/aside/README.md
- packages/components/aside/package.json
- packages/components/aside/src/aside.css
- packages/components/aside/src/aside.js
- packages/components/aside/stories/aside.stories.js
- packages/components/button/src/button.css
- packages/components/button/src/button.js
- packages/components/cover/src/cover.css
- packages/components/cover/src/cover.js
- packages/components/root/src/root.css
- packages/core/src/vars.css
- rollup.globals.json
> Create aside components

- packages/components/file-card/src/file-card.js
- packages/components/file-size/src/file-size.js
- packages/components/file-size/stories/file-size.happo.js
- packages/components/file-size/stories/file-size.stories.js
- packages/components/typography/src/typography.css
- packages/components/typography/src/typography.js
- packages/components/typography/src/utils/constants.js
- packages/components/typography/stories/typography.happo.js
- packages/components/typography/stories/typography.stories.js
- Replace color with type to make it consistent with other components
- Add disabled and disabled-active type colors
- Add tooltip support when the text is added by slot
> Refactor Typography component

- index.css
- index.html
- package-lock.json
- package.json
- packages/components/icon/src/icon.css
- packages/components/icon/src/utils/constants.js
- packages/components/list-item/README.md
- packages/components/list-item/package.json
- packages/components/list-item/src/list-item.css
- packages/components/list-item/src/list-item.js
- packages/components/list-item/stories/list-item.happo.js
- packages/components/list-item/stories/list-item.stories.js
- packages/components/typography/src/typography.css
- rollup.globals.json
list item component:
- title
- subtitle
- disabled
- selectable
- selected
- dir
- icon or icon-left
- icon-right
> Add list item component

- index.html
- packages/components/aside/src/aside.js
- packages/components/aside/src/utils/constants.js
- packages/components/aside/src/utils/index.js
- packages/core/src/core.js
- packages/core/src/utils/constants.js
> Add onClose and onClosed events into aside

- Repofile
> Disable continuous-integration/travis-ci/pr

- index.html
- packages/components/aside/src/aside.css
- packages/components/aside/src/aside.js
- packages/components/aside/stories/aside.stories.js
- packages/components/button/src/button.js
- packages/components/note/src/note.css
- packages/components/note/src/note.js
We need to ask the designer about the close icon and other stuff.
@esmailpour-hosein
> Integrate aside with note

- package.json
Runs
`clean`
`clean-node-modules`
`lerna bootstrap`
in sequence
> Add clean-install script

- plop-templates/components/{{kebabCase name}}/stories/{{kebabCase name}}.happo.js
- plop-templates/components/{{kebabCase name}}/stories/{{kebabCase name}}.stories.js
> Update plop story template

- README.md
> Add the missing information from the `how to use it` section

- index.html
- packages/components/aside/README.md
- packages/components/aside/src/aside.js
- packages/components/aside/src/utils/constants.js
- packages/components/aside/stories/aside.stories.js
- Removed the unused open/opened event name
- Changed the event name to be consistent with other component/standard
- Set default value for visible to true in storybook
- Added tables for props, events and slots in readme
- Used readme file for the notes inside all the story of the aside
> Refactor the ts-aside and add notes to its storybook

- packages/components/icon/src/assets/icons/checkmark.svg
- packages/components/icon/src/assets/icons/index.js
- packages/components/icon/stories/icon.stories.js
- packages/components/list-item/src/list-item.js
- packages/components/list-item/stories/list-item.stories.js
Add checkmark icon
Replace icon options from icons list of the component
Add reflect: true to all properties
- To reflect the changes in the element that was applied through js
- Like the one in the storybook
Add menu story
- Add story of multiple list-item together which forms a menu
> Add menu story to list-item and checkmark icon

- packages/components/list-item/stories/list-item.stories.js
Fixed the disabled selection
Removed select knobs since user can click and select
> Improve menu story

- index.html
- package-lock.json
- package.json
- packages/components/spinner/README.md
- packages/components/spinner/package.json
- packages/components/spinner/src/spinner.css
- packages/components/spinner/src/spinner.js
- packages/components/spinner/src/utils/constants.js
- packages/components/spinner/src/utils/index.js
- packages/components/spinner/stories/spinner.stories.js
- packages/core/src/vars.css
- rollup.globals.json
@esmailpour-hosein @aleks-elkin 
The design: 
https://app.goabstract.com/projects/17656740-ef81-11e6-be9b-53fd126a2b67/branches/4fbfb9d0-8e6b-11e8-8364-85a081a4e526/commits/8530c84be19318c783bcd234c32feb6c6257f55c/files/B1F5A5FD-B3D9-474C-9001-3A630EAB190A/layers/343E0B21-7A33-4BE1-A03F-A494D7FBC2A3?mode=design
> Add spinner component

- index.html
- packages/components/aside/src/aside.css
- packages/components/aside/src/aside.js
- packages/components/aside/stories/aside.stories.js
- packages/components/spinner/src/spinner.css
@esmailpour-hosein @aleks-elkin 
#170
> Use spinner in the aside

- README.md
@esmailpour-hosein @aleks-elkin
> Change readme of publishing

- .storybook-happo/utils.js
- index.html
- package-lock.json
- package.json
- packages/components/icon/src/assets/icons/close.svg
- packages/components/icon/src/assets/icons/index.js
- packages/components/icon/src/icon.css
- packages/components/icon/src/utils/constants.js
- packages/components/tab/README.md
- packages/components/tab/package.json
- packages/components/tab/src/tab.css
- packages/components/tab/src/tab.js
- packages/components/tabs/README.md
- packages/components/tabs/package.json
- packages/components/tabs/src/tabs.css
- packages/components/tabs/src/tabs.js
- packages/components/tabs/src/utils/constants.js
- packages/components/tabs/src/utils/index.js
- packages/components/tabs/stories/tabs.happo.js
- packages/components/tabs/stories/tabs.stories.js
- packages/components/typography/src/typography.css
- packages/core/src/core.js
- rollup.globals.json
> Tabs component

- index.html
- package-lock.json
- package.json
- packages/components/header/src/header.css
- packages/components/header/src/header.js
- packages/components/modal/README.md
- packages/components/modal/package.json
- packages/components/modal/src/modal.css
- packages/components/modal/src/modal.js
- packages/components/modal/src/utils/constants.js
- packages/components/modal/src/utils/index.js
- packages/components/modal/stories/modal.happo.js
- packages/components/modal/stories/modal.stories.js
- packages/components/root/src/root.css
- packages/components/root/stories/root.happo.js
- packages/components/root/stories/root.stories.js
- packages/components/tabs/package.json
- packages/core/package-lock.json
- rollup.globals.json
Added a modal component according to the NAV-60 Jira ticket.
- two sizes: large (take the whole page with 20px padding) and medium (padding 25% from left and right, 12,5% from top and bottom)
- slots for note, main and footer.
- can be opened/closed via the "data-visible" property or the call functions open()/close()
- Emit events for start and finish of the animation of open/close.
P.S.: also in this PR changed one js function in the index.html to run without errors in IE11.
> Add initial implementation of a modal component

- README.md
- package-lock.json
- package.json
> Add release command

- index.html
- package-lock.json
- packages/components/document-card/src/document-card.css
- packages/components/document-card/src/document-card.js
- packages/components/document-card/stories/document-card.happo.js
- packages/components/document-card/stories/document-card.stories.js
- packages/components/table/src/table.css
- packages/components/table/stories/table.happo.js
- packages/components/table/stories/table.stories.js
Fixed styles related to the table element
> COL-1784: Add conversations into Messages app

- index.html
- package-lock.json
- package.json
- packages/components/radio-group/README.md
- packages/components/radio-group/package.json
- packages/components/radio-group/src/radio-group.css
- packages/components/radio-group/src/radio-group.js
- packages/components/radio-group/src/utils/constants.js
- packages/components/radio-group/src/utils/helper-functions.js
- packages/components/radio-group/src/utils/index.js
- packages/components/radio-group/stories/radio-group.happo.js
- packages/components/radio-group/stories/radio-group.stories.js
- packages/components/radio/README.md
- packages/components/radio/package.json
- packages/components/radio/src/radio.css
- packages/components/radio/src/radio.js
- packages/components/radio/src/utils/constants.js
- packages/components/radio/src/utils/index.js
- packages/components/radio/stories/radio.happo.js
- packages/components/radio/stories/radio.stories.js
- packages/core/src/utils/constants.js
- packages/core/src/vars.css
- rollup.globals.json
Finished the radio button component (ts-radio, ts-radio-group). I would like to get any feedback, how to make it better. 
Currently, it supports all features of _ts-ui_ radio button component and has the same visual style. It support controlling via keyboard arrows when element focused. The internal structure of _ts-radio-group_ described as ts-radio HTML elements in the slot.
I have one idea: maybe we can make it more declarative and describe a structure with the data property. It's not so useful feature, but we can add it later.
`<ts-radio-group data="[{
label,
value,
checked,
disabled
}, ...]"> </ts-radio-group>`
> Radio button, radio group components

- packages/components/app-icon/src/app-icon.css
- packages/components/app-icon/src/app-icon.js
- packages/components/app-icon/src/utils/constants.js
- packages/components/app-icon/src/utils/index.js
- packages/components/app-icon/stories/app-icon.happo.js
- packages/components/app-icon/stories/app-icon.stories.js
add large size (60x60px) to ts-app-icon
> add sizes to ts-app-icon

- index.html
- package-lock.json
- packages/components/modal/src/modal.css
- packages/components/modal/src/modal.js
Add `hide-header` attribute to the Modal
In smaller screen make the Modal bigger (Temp till we get the actual design)
*Note: In media query selector we can't use CSS native variables.
> Make Modal header optional 

- index.html
- package-lock.json
- package.json
- packages/components/input/README.md
- packages/components/input/package.json
- packages/components/input/src/input.css
- packages/components/input/src/input.js
- packages/components/label/README.md
- packages/components/label/package.json
- packages/components/label/src/label.css
- packages/components/label/src/label.js
- packages/core/src/vars.css
- rollup.globals.json
It is only some css on the input. I will going to make storybook and happo story when we have ts-from which includes all the elements we have. 
@esmailpour-hosein @kirill-kolombet @aleks-elkin
> Make ts-input for form elements

- package-lock.json
- packages/components/modal/README.md
- packages/components/modal/src/modal.css
- packages/components/modal/src/modal.js
- packages/components/modal/stories/modal.happo.js
- packages/components/modal/stories/modal.stories.js
Added a property to remove the default paddings of main content in a `ts-modal` component.
> Added a noPadding property to a modal

- package-lock.json
- packages/components/document-card/src/document-card.css
- packages/components/input/package.json
- packages/components/label/package.json
- packages/components/modal/src/modal.css
- packages/components/pager/src/pager.css
- packages/core/src/utils/env-variables.json
- rollup.config.js
Added a file `env-variables.json` to specify the global env variables for CSS.
- Spec: https://drafts.csswg.org/css-env-1/#env-function
- MDN article: https://developer.mozilla.org/en-US/docs/Web/CSS/env
- PostCSS plugin (part of postcss-preset-env): https://github.com/csstools/postcss-env-function
Also updated `package-lock.json` to use actual versions of elements.
> Added global css env variables

- package-lock.json
- packages/components/button/README.md
- packages/components/button/src/button.js
Before it relied on click event on the component which didn't respect
the disabled and busy state of the component.
Used button-click instead of click to not cause any breaking change
fix #250
> Dispatch button-click custom event

- package-lock.json
- packages/components/tab/src/tab.css
- packages/components/tabs/src/tabs.css
To make it possible for developers to change the default padding of content in 
edge cases.
> NAV-161  ts-tabs: Move content padding to ts-tab host

- packages/components/checkbox/src/checkbox.js
Added a handler for click event to update the `checked` property status of checkbox.
> Added a checkbox-changed event to checkbox

- package-lock.json
- packages/components/file-uploader-input/package.json
- packages/components/file-uploader-input/src/file-uploader-input.js
Found a similar issue in lit-html repository: https://github.com/Polymer/lit-html/issues/1015
but none of suggested solutions are worked for me.
So for this case I decided to replace this directive with simple `if`.
> NAV-177: relpaced ifDefined directive by conditional rendering

- packages/components/list-item/src/list-item.css
- packages/components/list-item/src/list-item.js
- packages/components/list-item/stories/list-item.happo.js
- packages/components/list-item/stories/list-item.stories.js
- packages/components/typography/src/typography.css
NAV-240 Fix font weight of title in list-item
> NAV-239 Make selected state icon customizable in list-item

- package-lock.json
- package.json
- packages/components/aside/src/aside.css
Also fixed the development server issue
> [NAV-536] [Aside] Fix Aside component on mobile devices in Elements

- catalog-info.yml
Add catalog-info.yml to enable indexing in backstage.
> [APPEBL-507] Add catalog-info.yml for backstage.io

- packages/components/checkbox/src/checkbox.css
- packages/components/checkbox/src/checkbox.js
- packages/components/checkbox/stories/checkbox.happo.js
- packages/components/checkbox/stories/checkbox.stories.js
> Add the readonly state for checkbox

- package.json
- packages/components/checkbox/README.md
- packages/components/select/README.md
- packages/components/text-field/README.md
- scripts/from-src/get-properties.js
- scripts/helpers.js
- Ran update-readme script, to not cause unclean directory issue on release
- Add update-readme script to pre commit hook, to enforce updated readme files
- Fix wrong property description, if one property name was substring of another one
> Update readme files

- packages/components/cover/README.md
- packages/components/list-item/src/list-item.js
- Remove default tooltip from `list-item`
- Add the `Cover` readme file
> Remove default tooltip from `list-item`

- .storybook/main.js
- .storybook/manager.js
- package-lock.json
- package.json
- packages/components/confirmation-prompt/README.md
- packages/components/confirmation-prompt/package.json
- packages/components/confirmation-prompt/src/confirmation-prompt.css
- packages/components/confirmation-prompt/src/confirmation-prompt.js
- packages/components/confirmation-prompt/src/utils/index.js
- packages/components/confirmation-prompt/src/utils/translations.js
- packages/components/confirmation-prompt/stories/confirmation-prompt.happo.js
- packages/components/confirmation-prompt/stories/confirmation-prompt.stories.js
- packages/components/help-text/README.md
- packages/components/help-text/src/help-text.js
- packages/components/help-text/src/utils/index.js
- packages/components/help-text/src/utils/selectors.js
- packages/components/text-field/README.md
- packages/components/text-field/src/text-field.js
- plop-templates/components/{{kebabCase name}}/stories/{{kebabCase name}}.stories.js
- rollup.globals.json
> [PEAA-520] Add confirmation prompt component

- packages/components/help-text/README.md
- packages/components/help-text/src/help-text.js
PS: We should move the update-readme script call to another step/place. I suggest we add it to GHA, and let it update and commit the changes to the readme files. For this we probably need an appropriate way to let some component have a custom section or overwrite some parts of the generated readme.
> Update help-text readme file

- .github/workflows/commit-lint.yml
- .husky/commit-msg
- .husky/pre-commit
- commitlint.config.js
- package-lock.json
- package.json
- Migrated husky from v4 to v7 (there are some breaking changes).
- Added a commitlint package to validate commit messages with conventional commits standard. It will be used later to make automatic semantic releases based on conventional changelog with lerna. Documentation about the format: https://www.conventionalcommits.org/en/v1.0.0/
- Added a GHA to automatically check commit messages in each PR.
> Migrated to husky v7 and added a commitlint with GHA check for each PR

- .github/workflows/release.yml
Fixed the release.yml file format.
> PEAA-163: deleted a duplicate "name" property

- packages/components/action-select/src/action-select.css
- packages/components/action-select/src/action-select.js
- packages/components/board/README.md
- packages/components/board/index.html
- packages/components/board/src/board.css
- packages/components/board/src/board.js
- packages/components/board/stories/board.happo.js
- scripts/helpers.js
- scripts/update-readme-files.js
- [PEAA-755] Add header-actions slot to ts-board
- Fix the action-select trigger button not being aligned vertically
- Make the document-generator to just log in debug mode
[PEAA-755]: https://tradeshift.atlassian.net/browse/PEAA-755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [PEAA-755] Add header-actions slot to ts-board

- package-lock.json
Looks like our package-lock.json file got out of sync with package.json and release failed because of that.
Updated package-lock.json to fix the release pipeline.
> fix: fix package-lock file

- packages/components/action-select/types/action-select.d.ts
- packages/components/basic-table/types/basic-table.d.ts
- packages/components/confirmation-prompt/types/confirmation-prompt.d.ts
- packages/components/date-picker/types/date-picker.d.ts
- packages/components/file-uploader-input/types/file-uploader-input.d.ts
- packages/components/help-text/types/help-text.d.ts
- packages/components/note/types/note.d.ts
- packages/components/select-menu/types/select-menu.d.ts
- packages/components/select/types/select.d.ts
- packages/components/text-field/types/text-field.d.ts
- scripts/generate-types.js
Definition `[]` means empty array, and definition `any[]` means array with any values, which is more accurate.
> fix: changed the array type in d.ts files from '[]' to 'any[]'

- index.html
- package-lock.json
- package.json
- packages/components/tag/README.md
- packages/components/tag/index.html
- packages/components/tag/package.json
- packages/components/tag/src/tag.css
- packages/components/tag/src/tag.js
- packages/components/tag/stories/constants.js
- packages/components/tag/stories/tag.happo.js
- packages/components/tag/stories/tag.stories.js
- packages/components/tag/types/react-types.d.ts
- packages/components/tag/types/tag.d.ts
- plop-templates/components/{{kebabCase name}}/stories/{{kebabCase name}}.happo.js
- rollup.globals.json
I didn't add storybook nor a happo test. I want to discuss and possibly merge the component first
> [PEAA-169] Add tag element

- packages/components/overlay/src/overlay.js
https://tradeshift.atlassian.net/browse/PEAA-1009
> fix(select): positions select overlay from bottom up if it opens upwards

- package-lock.json
- package.json
lerna@^5.1.3 works with our setup in node 16/npm 8
> chore: update lerna to v5

- packages/components/icon/src/icon.js
In some configurations of webpack it can inline svg to dynamically imported modules.
I added a check for this case: if we got valid svg string we will use it as an icon svg, otherwise we will try to use imported string as Url to fetch svg.
> PEAA-1120: add a check for inlined svg strings when dynamically resolve a module

- package-lock.json
- package.json
fix: [VULN-3898] - [elements] parse-url has vulnerabilities
[VULN-3898]: https://tradeshift.atlassian.net/browse/VULN-3898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: [VULN-3898] - [elements] parse-url has vulnerabilities

- package-lock.json
Update terser to fix vulnerabilities
> Fix VULN-4068: update terser to fix vulnerabilities

- .github/renovate.json
- .github/workflows/main.yml
- .github/workflows/sonar.yml
- Jenkinsfile
- Repofile
chore(gha): clean-up Jenkinsfile (PEAA-1655)
> chore(gha): clean-up Jenkinsfile (PEAA-1655)

- .github/workflows/main.yml
chore(gha): rename jobs (PEAA-1655)
> chore(gha): rename jobs (PEAA-1655)
