Tradeshift/elements

package.json

Use the specific version of `@commonshost/server` to fix the `Cannot find module 'node-fetch'` issue on start which caused by their new release `6.10.0`

Use the specific version of `@commonshost/server`

---

packages/components/file-card/src/file-card.css

Before this the file card would get more space than parent in the `full` size based on the filename.
Now it fits the parent container

Force the file card to fit the container

---

README.md

There was an issue with older versions of the `tradeshift-ui` and `elements` in IE11 which was fixed by this:
>Fix the issue with web components inside ie11 When we used ts-ui and elements at the same time in ie11 it caused this error: Invalid Calling Object This will stop the web component crashing and not being able to be added after loading the ts-ui ([616bd6f](https://github.com/Tradeshift/tradeshift-ui/commit/616bd6fbcc2b9f44b2e918ba97941d8058b57b2b))

Add compatible Tradeshift-ui version to readme file

---

packages/components/aside/package.json
packages/components/button-group/package.json
packages/components/button/package.json
packages/components/card/package.json
packages/components/checkbox/package.json
packages/components/cover/package.json
packages/components/file-card/package.json
packages/components/file-size/package.json
packages/components/file-uploader-input/package.json
packages/components/file-uploader-input/src/file-uploader-input.js
packages/components/help-text/package.json
packages/components/icon/package-lock.json
packages/components/icon/package.json
packages/components/list-item/package.json
packages/components/note/package.json
packages/components/note/src/note.js
packages/components/progress-bar/package.json
packages/components/root/package.json
packages/components/search/package.json
packages/components/spinner/package.json
packages/components/spinner/src/spinner.js
packages/components/tooltip/package.json
packages/components/typography/package.json
packages/core/package-lock.json
packages/core/package.json
plop-templates/components/{{kebabCase name}}/package.json
rollup.config.js

Added the additional rollup config to build ES6 module for each component.
In this format all dependencies are not included in the result file of component, so the size of each component is smaller and duplicated components in the third-party applications will be loaded only once.
I built a small example with several elements and created two bundles:
with UMD modules(current master):
with es6 modules(this PR):

Added es6 modules to build config.

---

packages/components/header/src/header.css
packages/components/header/stories/header.stories.js

@esmailpour-hosein @aleks-elkin 
I looked over the Header element. Here are a few minor visual bugs:
vertically center the icon
border at the bottom
right-to-left knob
https://tradeshift.atlassian.net/browse/NAV-62

vertically center the icon; border at the bottom; right-to-left knob

---

packages/components/note/stories/note.stories.js

RTL checkbox in the [ts-note storybook](https://tradeshift.github.io/elements/?path=/story/ts-note--default) **didn't change component direction on click**. 
I suggest the problem is in the usage of outdated RTL property in the 'ts-note' storybook. Property 'rtl' was changed to 'dir' in note component, but the storybook code was not updated. 
Fixed using dir property.

Fixed broken rtl checkbox for note story

---

packages/components/aside/src/aside.js
packages/components/modal/src/modal.js
packages/core/src/core.js
packages/core/src/utils/behaviors.js
packages/core/src/utils/constants.js
packages/core/src/utils/helper-functions.js
packages/core/src/utils/index.js

[This issue](https://github.com/Tradeshift/elements/issues/158) asks to make aside/modal behavior on `ESC` press **the same** as users have with tradeshift-ui.
- Pressing `ESC` closes **all opened** asides/modals (not only the top one)
- Closing with `ESC` shortcut works even if **input currently focused**.
- Possibility to turn off `ESC` shortcut with _no-close-on-esc-key_ boolean attribute
- While IME composition is active, `ESC` is used for stopping the composition, so we won't close the panel on the press of it. 
Maybe there is a better way to do it is as it was done in the _polymer_ overlay component - _iron-overlay-behavior_. To have some behavior **shared between components** that track all opened asides/modals and can close on `ESC` the last one.

Add close on escape press for aside/modal component

---

index.html
packages/components/tabs/src/tabs.js

Prevented _event propagation_ from nested tabs to their parents. Stopped _event bubbling_ after first event handling, to prevent any parent tabs from the catching tab switching event from children _tabs_ components
I suppose I found another bug with nested tabs - a parent should query only **direct** children, not all nested ones, so I added direct children getter helper - `directChildrenTabs`.
Added to _index.html_ example of nested tabs.

Nested tabs

---

index.html
packages/components/table/src/table.js

Replaced `Array.prototype.includes()` by `Array.prototype.some()` to natively support IE11.
Also removed the shorthand functions in object literals, which are not supported by IE11.

Improved support of IE11 in table and index.html

---

index.html
packages/components/button/src/button.css
packages/components/button/src/button.js
packages/components/button/stories/button.stories.js
packages/components/icon/src/icon.css
packages/components/icon/src/utils/constants.js
packages/components/icon/stories/icon.stories.js

Made simple action button implementation **inside** _ts-button_.
Currently, we need only default _gray_ state. It's implemented as `type="text"` button with the icon specified. 
Normal:
Hover:
Pressed:

NAV-61 action button style for ts-button component

---

packages/components/search/src/search.js

Fixed in a `ts-search` component the emitting of the "idle" event on initial render and re-render with the same value.

Added checks for initial update and re-render of search component

---

packages/components/list-item/src/list-item.css
packages/components/list-item/src/list-item.js
packages/components/list-item/stories/list-item.happo.js
packages/components/list-item/stories/list-item.stories.js

- Allows ts-list-item to be able to receive a ts-app-icon (as a slot) instead of the lelft icon shown in a list item.
- Added no-wrap attribute to ts-list-item, in order to truncate the subtitle after one line

list-item accepts slot for ts-app-icon

---

packages/components/pager/stories/pager.stories.js
packages/components/spinner/README.md
packages/components/spinner/src/spinner.js
packages/components/spinner/stories/spinner.stories.js

- Fix unresponsive visible property
Based on the lit-element documentation:
The component’s render method can return anything that lit-html can render.
Typically, it returns a single TemplateResult object
(the same type returned by the html tag function).
- Update readme file of spinner
- Add a bit of margin in storybook of pager to make tooltip visible

Fix unresponsive visible property on spinner

---

packages/components/cover/src/cover.css
packages/components/modal/src/modal.css
packages/components/modal/src/modal.js
packages/core/src/vars.css

Changed z-index of the modal to be below the aside.
The same behaviour we have in TS-UI.
https://github.com/Tradeshift/tradeshift-ui/blob/485f88919cec5ee6dcdcc47f9bb0cd78a1bc224d/src/runtime/less/ts-modals.less#L3
https://github.com/Tradeshift/tradeshift-ui/blob/626bbd3357c057608ec40cc8779ce0be76ab04dd/src/runtime/less/ts-variables.less#L41

Changed the z-index of modal to be below aside.

---

package-lock.json
packages/components/board/src/board.css
packages/components/board/src/board.js
packages/components/board/stories/board.stories.js
packages/core/src/vars.css

- Added default white background for a board element. It is defined on `:host` level, so developers can change it easily.
- Background for header will be always white and text-color will be black so the host settings will not affect the header.
- Changed box-shadow to the same we have in ts-ui.
- Fixed the story to correctly render content knob.
Some notes: for the best rendering I had to put shadow and border-radius on `:host` level and add the `overflow:hidden` to clip the inside content by corner borders. Downside of this approach is that developers can mess up with that.
Default board:
Board and parent with custom background:
Board with custom background for content and parent with custom background:

fix: board: added default bg and changed shadow

---

packages/components/checkbox/src/checkbox.css
packages/components/checkbox/src/checkbox.js
packages/components/checkbox/stories/checkbox.happo.js
packages/components/checkbox/stories/checkbox.stories.js

- Fixed #275 
- Fixed a `checked` state management. Before there could be unexpected behaviour:
- render checkbox in `checked` state
- User unchecks it.
- set `checked` attribute from code.
- Now it will have a `checked` attribute but will render unchecked. If user will click on it, a `checked` attribute removed but checkbox rendered in checked state.
- Added a few knobs to a story.

fix(checkbox): improved layout. Fixed a checked state management

---

index.html
packages/components/basic-table/stories/basic-table.happo.js
packages/components/basic-table/stories/basic-table.stories.js
packages/components/status/src/status.css
packages/components/status/src/status.js
packages/components/status/src/utils/constants.js
packages/components/status/stories/status.stories.js

The status label is missing 2 states - primary(blue) and the error state used to be orange (corresponding to warning) instead of red.
The naming of the status was not conforming to the naming conventions we use in other components.
This PR introduces the following naming + colors:
- ok -> changed to "success"
- note -> changed to "neutral"
- error -> changed color to red instead of orange
- warning (new) -> orange (the colors that previously belonged to error)
- primary -> blue

Aditional status classes

---

package-lock.json
packages/components/checkbox/src/checkbox.js

In the previous commit, I accidentally added the `event.stopPropagation()` method call for the `click` event, which is why all listeners outside the element stopped receiving this event.
Now I fix this.

fix(checkbox): returned a click event propagation

---

packages/components/file-uploader-input/src/file-uploader-input.js

We already hiding the Allowed formats help message when this property is undefined, but the component should have the same behaviour when the provided array of available extensions is empty.

NAV-412. Hide the Allowed formats message for empty array

---

packages/components/modal/src/modal.css

Now on mobiles all modals will have a same size: almost the whole screen with `@ts-unit-half` margins.

NAV-427. Modal. Improved sizes on a mobile.

---

package-lock.json
packages/components/dialog/package.json
packages/components/dialog/src/dialog.js
packages/components/radio-group/package.json
packages/components/tabs/package.json
packages/components/tabs/src/tabs.js

- Move peer deps to dependencies:
Based on the changes that have been done about peerDependencies in the npm@7 it caused error for projects that've being using the radio-group or tabs. `tab` and `radio` components are added to dependencies of `tabs` and `radio-group` since they are actually useless without those components and it makes developers life easier to just handle one dep if they only need those group components and not import the child component.
- fix: Add missing dependencies of dialog component

Fix peer dep issue with npm@7

---

packages/components/pager/src/pager.css

Fixed a mistake in css rule that blocks a transition of ts-pager to mobile state. Now it should work fine.

[PEAA-57] fix(pager): fixed a css media query for mobile devices

---

.storybook-happo/.babelrc
.storybook-happo/preview.js
package-lock.json
package.json
packages/components/basic-table/src/basic-table.js
packages/components/basic-table/stories/basic-table.happo.js

Recently noticed, that PRs cannot be built on Travis because Happo falied with timeout when tries to get snapshots from IE11.
Apparently, I broke something in Happo setup when updated storybook to the latest version in PR #307.
IE 11 fails to finish with some cryptic errors, but explicit import of `core-js` with polyfills solved it.
I had to explicitly add `core-js` to `devDependencies` which triggered big changes in package-lock.json (deduplication I think).

chore(happo): Explicitly added import of core-js to load IE 11 polyfills.

---

catalog-info.yml

Updated the owner to the actual one: `partner-enablement-and-apps`.
Fixes #321

chore(backstage): Updated catalog-info with the correct owner

---

package-lock.json
package.json
packages/components/popover/README.md
packages/components/popover/package.json
packages/components/popover/src/popover.css
packages/components/popover/src/popover.js
packages/components/popover/stories/popover.happo.js
packages/components/popover/stories/popover.stories.js
rollup.globals.json
scripts/helpers.js

Added an initial implementation of the popover element.
There are two ways to close the popover: by pressing the `X` button on top right of the popover or via API by setting `opened` property to `false`.
If the anchor element is defined, it will try to position the popover relative to this anchor. Developer should specify `placement` to define where the popover should be rendered.
If the anchor is not specified, popover will be placed absolutely, based on the values in `positionLeft` and `positionTop`, which accepts any valid css syntax, e.g. `50px`, `50%`, `calc(100%-50px)`.
Screenshot:

feat(popover): PEAA-316. Added an initial implementation for popover.

---

packages/components/popover/package.json
plop-templates/components/{{kebabCase name}}/package.json

I think this field is required for publishing to the Github npm registry. I forgot to add it to a new `popover` element and publishing failed on this component.
Added this field to `popover` + added it to a package.json template so next components will have it from the beginning.

Added a "repository" field to a package.json element's template

---

packages/components/tooltip/src/tooltip.css

Position of the tooltip has to be consistent and not relative to the content of the child. Based on the design, it has to be 10px away from the anchor, in all positions.
https://www.figma.com/file/GIQREuPZ2iGA1kRpjlpehT/UI-Components?node-id=1610%3A35588

fix: Make tooltip position consistent from the anchor

---

package-lock.json
packages/components/radio-group/src/radio-group.css

By default browsers have additional padding and margin for standard html fieldset element that we use in radio-group. But our design system have a different settings, so we reset this predefined values and set it as in our design system.

fix(radio-group): PEAA-56: reset padding and margin for fieldset.

---

package-lock.json
packages/components/confirmation-prompt/src/confirmation-prompt.js
packages/components/modal/src/modal.js

The confirmation prompt couldn't get reopened because of an issue with modal close event which was emitting on `data-visible` prop change, that wasn't the correct way to handle it. Moved the close event of the modal to close method to just be emitted on deliberate actions of user for dismissing the modal. 
In the confirmation prompt knowing when the modal gets `closed` is enough.

Fix: confirmation prompt reopening issue

---

packages/components/list-item/src/list-item.js

With the need of using icons out of UI library icons (eg. @ icon) from design team, it no longer seems legit restriction to only have icons from Elements or AppIcon.

Remove restriction for list-item icon slot

---

packages/components/select/src/select.js

Make a search in a select component not case-sensitive by calling `toLowerCase()` and comparing results.

fix(select): make search in a select case-insensitive

---

.github/workflows/release.yml

Change npm token used at publish step to a specially created for publish and release purposes.

ci: change npm token used at publish step to a specially created for release

---

packages/components/select/src/select.js

When we try to change the selection in js code via property `selected`, the text with selected value, displayed in the input, do not updated immediately.
Fixed this issue. Now, every time when the `selected` property is changed, a component will refresh the displayed text according to actual selection.

fix: fixed incorrectly displayed value in a select component when a selection changed in property

---

package-lock.json
package.json
packages/components/action-select/README.md
packages/components/action-select/package.json
packages/components/action-select/src/action-select.css
packages/components/action-select/src/action-select.js
packages/components/action-select/stories/action-select.happo.js
packages/components/action-select/stories/action-select.stories.js
packages/components/icon/src/assets/icons/index.js
packages/components/icon/src/assets/icons/more.svg
rollup.globals.json

Added a new component, `action-select` that will show a dropdown menu of actions bounded to the provided anchor element. This anchor element should be inside the default slot, otherwise the default ts-icon with icon `more` will be rendered.
Example of usage with anchor element (in this case it is a `ts-button`): 
```html
<ts-action-select>
<ts-button>Button</ts-button>
</ts-action-select>
```
Also, added a new icon called `more` that looks like `...` and is similar to the icon `ts-icon-other` from Tradeshift-UI.

PEAA-360: add a action-select component to the library

---

index.html
packages/components/action-select/README.md
packages/components/select-menu/README.md
packages/components/select-menu/src/select-menu.js
packages/components/select/README.md
packages/components/select/src/select.js
packages/components/select/stories/select.happo.js
packages/components/select/stories/select.stories.js

adds option to select (and implicitly to select-menu) to allow direct
items selections without a separate apply button
https://user-images.githubusercontent.com/1011245/133579804-0960d730-5770-4b43-861f-40e9de4e87d1.mov

feat(select): (PDV-1405) select items without confirmation apply button

---

packages/components/select/src/select.js
packages/components/select/stories/select.stories.js

when changed the attribute to snake case no-apply-button, it was
not propagated correctly to the select-menu used in the select
see also: PDV-1407

fix(select): no-apply-button attribute wrongly set on select-menu

---

packages/components/tab/README.md
packages/components/tab/src/tab.js
packages/components/tab/types/tab.d.ts
packages/components/tabs/src/tabs.js
packages/components/tabs/stories/tabs.stories.js

To let the developers more easily distinguish the tab (ex. e2e testing selectors), added the id property of ts-tab to the tab header that are generated by the ts-tabs and add the them to the tab button and pass it through as part of the payload of the tab-click event.

feat(ts-tabs): add id property to the tab button

---

packages/components/action-select/src/action-select.css

the white background overrides any other container color and is not
possible to change
if necessary the background color can be changed from a container
before:
after:

fix(action-select): remove background color

---

README.md
packages/components/action-select/index.html
packages/components/overlay/src/overlay.js

As documented in https://tradeshift.atlassian.net/browse/PEAA-842 , the ts-select-action dropout will in some cases miscalculate if it fits in on the right side of its anchor. The basic issue here is that the component tries to calculate that based on, among other factors, the width of the rendered dropout. So it depends on content, and even on wrapping that content. It will re-calculate on window resize, getting valid values.
The changes will reduce this wrong behaviour, but it is probably not bulletproof.
Another issue is that it would sometimes pull dropouts partly off-viewport (opening to the left on narrow enough screens). The changes fix that. The issue:
The issue referenced in the task:
.

[PEAA-842] Action select positioning issue on top-right corner in relative mode

---

packages/components/action-select/package.json
packages/components/confirmation-prompt/package.json
packages/components/date-picker-overlay/package.json
packages/components/date-picker/package.json
packages/components/dialog/package.json
packages/components/overlay/package.json
packages/components/popover/package.json
packages/components/select-menu/package.json
packages/components/select/package.json
packages/components/text-field/package.json
plop-templates/components/{{kebabCase name}}/package.json

Our new components did not contain type definitions references in their package.json and these typings did not published.
This Pr fixes this issue by adding missing types definitions and adjusting new component template to have them by default.

Add missing types for new components and fix new component template to add them by default

---

packages/components/progress-bar/stories/progress-bar.stories.js
packages/components/tab/stories/tab.stories.js
packages/components/tabs/stories/tabs.stories.js

- For `progress-bar` and `tabs` there was a typo causing the notes not being shown.
- For `tab` component since it didn't have a story because of its nature that would be useful with tabs component, and being included in tabs story. Added a simple text as story to both show how they can see the example and also get access to readme/notes from the storybook.

fix(storybook): fix missing notes for tabs, tab and progress-bar

---

packages/components/action-select/src/action-select.js
packages/components/date-picker/src/date-picker.js
packages/components/search/README.md
packages/components/search/src/search.js
packages/components/select/src/select.js

Added two fixes:
- updated the event comment in search component to reflect a new logic, that it now triggered when user selects an item from dropdown
- delete a closeOverlay reference after it is called because overlay already closed and it will throw an error on next call. It could happen in this case: 
- open select component (it will keep the reference to the function)
-  when it got attached to DOM and detached several times (e.g. in aside or modal) it will try to call this function again. But the overlay no longer exists (it got destroyed after first call).
If we remove this reference after a call it should solve the issue.

Update the event comment in search component and fix error in select-like components

---

index.html
packages/components/select-menu/README.md
packages/components/select-menu/src/select-menu.css
packages/components/select-menu/src/select-menu.js
packages/components/select-menu/types/select-menu.d.ts
packages/components/select/README.md
packages/components/select/index.html
packages/components/select/src/select.js
packages/components/select/src/utils/translations.js
packages/components/select/stories/select.happo.js
packages/components/select/stories/select.stories.js
packages/components/select/types/select.d.ts

- [feat(select): add case-sensitive filtering to select component](https://github.com/Tradeshift/elements/pull/420/commits/ee8182f4ca559e2815d6ee4e54f638e20b528dec) 
`caseSensitive` property or `case-sensitive` can be passed to the select and select-menu components to make the filtering/search case-sensitive.
- [feat(select): add custom filtering to select component](https://github.com/Tradeshift/elements/pull/420/commits/690abf8ff1cd4164dcfead0d33e1d49c0f934cab) 
Now it's possible to do custom filtering beside the basic filter that is done by default for item.title text. Now developers can listen to `filter-value-change` event, to get the user inputed value for search/filter and pass `filteredItems` to override the default internal filter/search through the already provided items. To …

[PEAA-592] Select: add custom filtering + minor bug fixes 

---

index.css
index.html
packages/components/button-group/README.md
packages/components/button-group/index.html
packages/components/button-group/src/button-group.css
packages/components/button-group/src/button-group.js
packages/components/button-group/stories/button-group.happo.js
packages/components/button-group/stories/button-group.stories.js
packages/components/button-group/types/button-group.d.ts
packages/components/button/README.md
packages/components/button/src/button.css
packages/components/button/src/button.js
packages/components/button/types/button.d.ts

Now it's possible to use the button-group in horizontal/inline mode with `inline`
property/attibute, which would make the buttons in the group aligned, margined
and wrapped properly.

feat(button-group): peaa-885 button-group support horizontal/inline mode

---

index.html
package-lock.json
packages/components/dialog/README.md
packages/components/dialog/index.html
packages/components/dialog/src/dialog.css
packages/components/dialog/src/dialog.js
packages/components/dialog/src/utils/constants.js
packages/components/dialog/src/utils/index.js
packages/components/dialog/stories/dialog.happo.js
packages/components/dialog/stories/dialog.stories.js
packages/components/dialog/types/dialog.d.ts
packages/components/modal/README.md
packages/components/modal/src/modal.js
packages/components/modal/types/modal.d.ts
packages/core/src/utils/constants.js

Task: https://tradeshift.atlassian.net/browse/PEAA-395
These changes add notification features to the dialog element:
A dialog can have a `notification` attribute and will have no cancel button, and if `no-buttons`, no buttons at all.
A `success` type `notification` will auto-close after 1500 ms, if not non-dismissable.
A `non-dismissable` notification or dialog cannot be closed except by clicking a button provided by the dialog/notification.
The changes also include a fix that makes auto-focusing a button ('accept' or 'cancel') work, although only in dialog (not notification) mode, and a new attribute is added to ts-modal, making closing on clicking the cover optional.

feat(dialog): adds notification options to dialog element

---

index.html
packages/components/button/index.html
packages/components/button/src/button.css
packages/components/radio-group/src/radio-group.css
packages/core/src/vars.css

Motivation: ts-buttons are lacking a border indicating focused state. In case type=secondary it makes a focused button look like plain text.
Note that letter-spacing is removed on the buttons, because there is no custom letter-spacing in the design. It improves readability IMO, but triggers a lot of happo snapshot changes.
Design: https://www.figma.com/file/v4lzSShpqzYtQ5aQRcKAmV/UI-Library---Clean-(New-system-without-documentation)?node-id=3453%3A1

fix(button): fixes missing/broken focus state styling

---

package-lock.json
packages/components/overlay/src/overlay.js

Issue: https://tradeshift.atlassian.net/browse/PEAA-915
The issue is about multi-selects, but in general, the ts-overlay is not positioned correctly vertically, because it does not consider scroll position. This fixes it.

[PEAA-915] fix ts multi select

---

packages/components/board/stories/board.happo.js
packages/components/button/src/button.js
packages/components/icon/stories/icon.happo.js
packages/components/radio/stories/radio.happo.js

Added a story with all available icons for `ts-icon` component. Some icons looks strange, it will be fixed in following PRs.

Add a happo story with all available icons

---

scripts/new-version.sh

Run the same install scripts that we have in release GHA, so it should solve the issue with unexpected changes in package-lock.json

Add install scripts to a new version script to avoid unexpected changes in package-lock

---

.storybook-happo/preview-head.html
.storybook/preview-head.html
package-lock.json
package.json

After we introduced npm overrides storybook has stop building successfully due to some inconsistency in dependencies.
I added the override for `react-syntax-highlighter` for no longer supported storybook addon `@storybook/addon-notes@5.3.21` to align with other storybook plugins and it seems to solve the issue.
Also, added an override for `trim-newlines` package to address the dependabot alert.

Fix storybook deploy

---

package-lock.json
package.json

`rollup-plugin-svgo` released a new version with upgrade in it's dependencies, so `nth-check` can be removed from overrides

Upgrade rollup-plugin-svgo to remove one override

---

.storybook/preview.js
packages/components/card/stories/card.stories.js

- fixed error with custom HTML in `ts-card` story. Made it the same way as we have in `ts-board` story.
- Made order of stories alphabetical. Documentation: https://storybook.js.org/docs/react/writing-stories/naming-components-and-hierarchy#sorting-stories

PEAA-1317: fix ts-card story and stories order

---

.github/workflows/main.yml

We need to install dependencies first to make sure scripts will use the correct version of lerna.

Install dependencies before bootstrap in GHA
